---
# tasks file for openshift-gls-gps-workshop

1.) copy kickstart to /tmp

2.) delete exiuting vms

3.) undefine existing vms

4.) delete existing storage 

5.) create vm

virt-install --name ${NAME} -description "${DESCRIPTION}" --os-type Linux --os-variant rhel7 --ram ${RAM} --vcpus ${VCPUS} --cpu host --accelerate --disk pool=ocp_images,bus=scsi,size=50,sparse=yes --controller scsi,model=virtio-scsi --graphics none --network network=ocp4-network --location /mnt/ocp_isos/rhel-8.1-x86_64-dvd.iso --initrd-inject=$(dirname $0)/${KICKSTART} --extra-args "ks=file:/${KICKSTART} console=ttyS0,115200" --boot --network network=ocp4-network,mac=${MAC} 

6.) start vm


