---
# tasks file for openshift-gls-gps-workshop

- name: copy kickstart file to hypervisor
  copy:
    src: "{{ role_path }}/files/hypervisor_libvirt/hypervisor_services_vm.ks"
    dest: "/tmp/hypervisor_services_vm.ks"
    owner: root
    group: root
    mode: '0644'
    backup: 'yes'

- name: destroy existing services vm on hypervisor
  shell: virsh destroy --domain services.{{ ansible_fqdn }}

- name: undefine existing services vm on hypervisor
  shell: virsh undefine --domain services.{{ ansible_fqdn }}

- name: delete existing services qcow2 file on hypervisor
  shell: rm -Rf /mnt/ocp_images/services.{{ ansible_fqdn }}.qcow2

- name: create new services vm on hypervisor
  shell: virt-install --name services.{{ ansible_fqdn }} -description "OCP 4 Services Machine" --os-type Linux --os-variant rhel7 --ram 8192 --vcpus 4 --cpu host --accelerate --disk pool=ocp_images,bus=scsi,size=50,sparse=yes --controller scsi,model=virtio-scsi --graphics none --network network=ocp4-network --location /mnt/ocp_isos/rhel-8.1-x86_64-dvd.iso --initrd-inject=/tmp/hypervisor_services_vm.ks --extra-args "ks=file:/tmp/hypervisor_services_vm.ks console=ttyS0,115200" --boot --network network=ocp4-network 


