- name: force reload of systemd configuration on hypervisors
  systemd:
    daemon_reload: yes

- name: start services on hypervisors
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop: "{{ hypervisor_systemd_services }}"
