---
# tasks file for openshift-gls-gps-workshop

- name: create directory for images on hypervisor.rhaw.io
  file:
    path: /mnt/ocp_images
    state: directory
    owner: root
    group: root
    mode: 0775

- name: create directory for isos on hypervisor.rhaw.io
  file:
    path: /mnt/ocp_isos
    state: directory
    owner: root
    group: root
    mode: 0775

- name: define storage pool as ocp_images on hypervisor.rhaw.io
  virt_pool:
    command: define
    name: ocp_images
    xml: "{{ role_path }}/files/hypervisor_libvirt/hypervisor_ocp_pool_images.xml"

- name: build storage pool as ocp_images on hypervisor.rhaw.io
  virt_pool:
    command: build
    name: ocp_images

- name: start storage pool as ocp_images on hypervisor.rhaw.io
  virt_pool:
    command: create
    name: ocp_images

- name: activate storage pool as ocp_images on hypervisor.rhaw.io
  virt_pool:
    state: active
    name: ocp_images

- name: autostart storage pool as ocp_images on hypervisor.rhaw.io
  virt_pool:
    autostart: yes
    name: ocp_images

- name: define storage pool as ocp_isos on hypervisor.rhaw.io
  virt_pool:
    command: define
    name: ocp_isos
    xml: "{{ role_path }}/files/hypervisor_libvirt/hypervisor_ocp_pool_isos.xml"

- name: build storage pool as ocp_isos on hypervisor.rhaw.io
  virt_pool:
    command: build
    name: ocp_isos

- name: start storage pool as ocp_isos on hypervisor.rhaw.io
  virt_pool:
    command: create
    name: ocp_isos

- name: activate storage pool as ocp_isos on hypervisor.rhaw.io
  virt_pool:
    state: active
    name: ocp_isos

- name: autostart storage pool as ocp_isos on hypervisor.rhaw.io
  virt_pool:
    autostart: yes
    name: ocp_isos

- name: define ocp4 network on hypervisor.rhaw.io
  virt_net:
    command: define
    name: ocp4-network
    xml: "{{ role_path }}/files/hypervisor_libvirt/hypervisor_ocp_network.xml"

- name: start ocp4 network on hypervisor.rhaw.io
  virt_net:
    command: create
    name: ocp_network

- name: activate ocp4 network on hypervisor.rhaw.io
  virt_net:
    state: active
    name: ocp_network

- name: autostart ocp4 network on hypervisor.rhaw.io
  virt_net:
    autostart: yes
    name: br_nat
